import turtle
v=turtle.Turtle()
v.speed(10)
def cycle1(x,y,z):

 turtle.bgcolor("black")

 v.lt(x)
 v.fd(y)
 v.rt(90)
 v.color(z)
 v.circle(44)
 v.pencolor("red")
 v.home()
v.begin_fill()

cycle1(120,50,"pink")
v.end_fill()
v.begin_fill()
cycle1(70,100,"violet")
v.end_fill()
v.begin_fill()
cycle1(50,110,"palegreen")
v.end_fill()
v.begin_fill()
cycle1(80,160,"skyblue")
v.end_fill()
v.begin_fill()
cycle1(90,120,"crimson")
v.end_fill()
v.begin_fill()
cycle1(95,200,"salmon")
v.end_fill()
v.begin_fill()
cycle1(105,210,"deeppink")
v.end_fill()
turtle.done()